name: Update SSM
concurrency:
  group: update-ssm
  cancel-in-progress: false
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment'
        required: true
        default: 'development'
        type: choice
        options:
        - development
        - staging
        - qa
      value:
        description: 'Add env in "KEY=VALUE" format'
        type: string

jobs:
  update-ssm:
    runs-on: ubuntu-latest
    steps:
      - name: Create new release branch
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        run: |
          echo  The values are
          echo ${{ inputs.environment }}
          for env in ${{ inputs.value }}; do \
            NAME=$(echo $env | awk '{split($0,a,"="); print a[1]}'); \
            VALUE=$(echo $env | cut -f 2- -d '=' | sed 's/"//g'); \
            aws ssm put-parameter --name "/temp/${{ inputs.environment }}/${NAME}" --value $VALUE --type "SecureString" --data-type "text" --overwrite; \
          done
