name: Update SSM
concurrency:
  group: update-ssm
  cancel-in-progress: false
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment'
        required: true
        default: 'development'
        type: choice
        options:
        - qa
        - staging
        - development
        - production
      service:
        description: 'Select the service'
        required: true
        default: 'shared'
        type: choice
        options:
        - shared
        - apionly
        - apigateway
        - mainservice
        - payments
        - documents
        - notifications
        - frontend-admin
      parameter:
        description: 'Add env in "KEY=VALUE" format'
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  update-ssm:
    runs-on: ubuntu-latest
    env:
      PREFIX: ""
    steps:
      - if: ${{ inputs.environment == 'production' }}
        run: echo "PREFIX=PRODUCTION_" >> $GITHUB_ENV
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets[format('{0}AWS_GITHUB_ROLE_ARN', env.PREFIX)] }}
          aws-region: us-west-2
      - name: Put envs on SSM - Parameter Store
        run: |
          export SSM_PREFIX="/shared/${{ inputs.environment }}"
          if [[ "${{ inputs.service }}" != "shared" ]]; then
            export SSM_PREFIX="/cbh-${{ inputs.service }}/${{ inputs.environment }}"
          fi
          for env in ${{ inputs.parameter }}; do
            NAME=$(echo $env | awk '{split($0,a,"="); print a[1]}')
            VALUE=$(echo $env | cut -f 2- -d '=' | sed 's/"//g')
            aws ssm put-parameter --name "${SSM_PREFIX}/${NAME}" --value ${VALUE} --type "SecureString" --data-type "text" --overwrite
          done
